package com.dora.security;

import com.dora.entities.AppUser;
import com.dora.repositories.AppUserRepository;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.JwtException;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.lang.NonNull;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.List;

/**
 * Extracts and validates a JWT from the Authorization header on every request.
 *
 * On success, builds a {@link CustomUserDetails} backed by the loaded {@link AppUser}
 * and sets it in {@link SecurityContextHolder}.  On any failure (missing/invalid/expired
 * token) the context is cleared and the filter chain continues — Spring Security's
 * access-decision machinery will then return 401 for protected paths.
 *
 * The login path is skipped entirely: no token is expected there.
 *
 * DB lookup: we load the {@link AppUser} so that {@link CustomUserDetails#getAppUser()}
 * returns a fully populated entity.  This gives downstream code (e.g. AuthService.getUserProfile)
 * access to tenantId and mfaEnabled without a second query.  The cost is one SELECT per
 * authenticated request; acceptable for the current load profile (and replaced by Cognito
 * token validation in LLD-16, which has no DB round-trip).
 */
@Component
public class JwtAuthFilter extends OncePerRequestFilter {

    private static final String BEARER_PREFIX = "Bearer ";
    private static final String LOGIN_PATH = "/api/v1/auth/login";

    private final DevJwtService jwtService;
    private final AppUserRepository userRepository;

    public JwtAuthFilter(DevJwtService jwtService, AppUserRepository userRepository) {
        this.jwtService = jwtService;
        this.userRepository = userRepository;
    }

    @Override
    protected boolean shouldNotFilter(@NonNull HttpServletRequest request) {
        // Use getRequestURI() — getServletPath() returns "" in MockMvc slice tests.
        return LOGIN_PATH.equals(request.getRequestURI());
    }

    @Override
    protected void doFilterInternal(@NonNull HttpServletRequest request,
                                    @NonNull HttpServletResponse response,
                                    @NonNull FilterChain filterChain)
            throws ServletException, IOException {

        String header = request.getHeader("Authorization");
        if (!StringUtils.hasText(header) || !header.startsWith(BEARER_PREFIX)) {
            // No bearer token — continue chain; Spring Security will reject if the path requires auth.
            filterChain.doFilter(request, response);
            return;
        }

        String token = header.substring(BEARER_PREFIX.length());
        try {
            Claims claims = jwtService.verify(token);
            String email = claims.getSubject();

            // Load user for tenant_id and mfa_enabled; roles come from the token claim.
            AppUser user = userRepository.findByEmail(email).orElseThrow(
                    () -> new JwtException("User not found for token subject: " + email));

            // Reject tokens for deactivated accounts (active=false soft-delete per LLD-02 §5).
            if (!user.isActive()) {
                SecurityContextHolder.clearContext();
                filterChain.doFilter(request, response);
                return;
            }

            @SuppressWarnings("unchecked")
            List<String> roleCodes = claims.get("roles", List.class);

            CustomUserDetails userDetails = new CustomUserDetails(user, roleCodes);
            UsernamePasswordAuthenticationToken authentication =
                    new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());

            SecurityContextHolder.getContext().setAuthentication(authentication);

        } catch (JwtException | IllegalArgumentException ex) {
            // Invalid, expired, or tampered token — clear context, let chain continue.
            // The 401 is generated by Spring Security's AuthenticationEntryPoint
            // configured in SecurityConfig, not here.
            SecurityContextHolder.clearContext();
        }

        filterChain.doFilter(request, response);
    }
}
